### ISSUE TITLE
Supported Kubernetes Versions outdated

### ISSUE THREAD

**Issue by Skaronator** [k0sproject/k0sproject.github.io#25]
Hi,

The Supported Kubernetes Versions are outdated https://k0sproject.io/ main page by 2 major versions.

![image](https://user-images.githubusercontent.com/2886913/180956968-6a943a66-afc5-42d6-a818-8fb1f1c9ad3b.png)

**Comment by Skaronator** [comment]
Also, Windows is no longer a Supported Host OS?

**Comment by twz123** [comment]
Thanks for reporting.

> Also, Windows is no longer a Supported Host OS?

It's a pending decision. There's an issue and a PR about removing Windows support, but those are on hold right now.
